### ISSUE TITLE
Add and test NordLEI witness/vlei-server configuration

### ISSUE THREAD

**Issue by 2byrds** [GLEIF-IT/vlei-verifier#11]

**Comment by ronakseth96** [comment]
The vlei-verifier verification service has been configured with the NordLEI witnesses provided by Daniel and deployed in the test environment.

**Comment by 2byrds** [comment]
We are including all public witnesses in combination here https://github.com/GLEIF-IT/vlei-verifier/blob/main/scripts/keri/cf/verifier-config-public.json
