### ISSUE TITLE
Verifier is not handling the case when user who submitted a credential has incorrect Context Role

### ISSUE THREAD

**Issue by aydarng** [GLEIF-IT/vlei-verifier#64]
When user submit the ECR credential with incorrect Contest Role the CredProcessState should be changed to have AUTH_FAIL state. Currently it's not handled. It can be handled during the precessEcr method call inside of the 'if' block
![image](https://github.com/user-attachments/assets/600916f7-2a5c-416f-abc8-7b88a4f08ce7)

**Comment by 2byrds** [comment]
Thank you for submitting @aydarng. I have moved that logic into a cred_filter method that will eventually be configurable, similar to our reg-pilot data generation. But for now, still some 'hard-coded' filtering and if its not an EBA Data Submitter then the AUTH_FAIL state should be set and will age off after a bit:
https://github.com/GLEIF-IT/vlei-verifier/pull/65/files#diff-f66b3a2dd0092a882248f8dcf64306ab10adc1bf69d8e0edada4afcb5e7b68ecR171
